### ISSUE TITLE
Unable to download database using cake

### ISSUE THREAD

**Issue by JohnKellyFerguson** [alphasights/cake#1]
When trying to download a database slice, I get the following error:

```
➜ pistachio git:(master) heroku cake:slice
Downloading database from S3...
PG::InvalidParameterValue: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
: CREATE DATABASE "alpha_dev" ENCODING = 'utf-8'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/schema_statements.rb:80:in `create_database'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:17:in `create'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:88:in `create'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:102:in `block in create_current'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:101:in `create_current'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/rubies/2.1.4/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.4/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.4/bin/rake:23:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"utf-8", "min_messages"=>"warning", "timeout"=>5000, "username"=>"JohnKellyFerguson", "database"=>"alpha_dev"}
PG::InvalidParameterValue: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
: CREATE DATABASE "alpha_test" ENCODING = 'utf-8'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/schema_statements.rb:80:in `create_database'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:17:in `create'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:88:in `create'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:102:in `block in create_current'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:101:in `create_current'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/rubies/2.1.4/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/opt/rubies/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.4/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.4/bin/rake:23:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"utf-8", "min_messages"=>"warning", "timeout"=>5000, "username"=>"JohnKellyFerguson", "database"=>"alpha_test"}
pg_restore: [archiver (db)] connection to database "alpha_dev" failed: FATAL:  database "alpha_dev" does not exist
```

**Comment by davegriffiths** [comment]
FYI guys this is public.
